# Postgres on GitHub

name: Test

on:
  push

jobs:
  js:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      run: |
        sudo apt install nodejs
        npm install pg
      
    - name: Test
      run: |
        sudo systemctl start postgresql.service
        sudo -i -u postgres psql < load.txt
        nodejs select1.js

  perl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      run: |
        sudo cpan -T -i Data::Table::Text Digest::SHA1 Date::Manip
    
    - name: InstallJs
      run: |
        sudo apt install nodejs
        npm install pg
      
    - name: Test
      run: |
        sudo systemctl start postgresql.service
        cat load.txt
        sudo -i -u postgres psql < load.txt > output.txt
        cat output.txt
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} perl upload.pl 
        
  
