# Postgres on GitHub

name: Test

on:
  push

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install
      run: |
        sudo cpan -T -i Data::Table::Text Digest::SHA1

    
    - name: Test
      run: |
        sudo systemctl start postgresql.service
        sudo -i -u postgres psql < load.txt
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} perl upload.pl 
        
