# Postgres on GitHub

name: Test

on:
  push

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Test
      run: |
        GITHUB_TOKEN='aaaa' echo $GITHUB_TOKEN 
        sudo systemctl start postgresql.service
        sudo -i -u postgres psql < load.txt
        
