# Postgres on GitHub

name: Test

on:
  push

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo cpan -T -i JSON Digest::SHA1 Date::Manip
        
    - name: Test
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        
        sudo systemctl start postgresql.service
        sudo -i -u postgres psql < load.txt > output.txt
        GITHUB_REPOSITORY=${{ secrets.GITHUB_TOKEN }} perl upload.pl
        
