# Build and test CPAN module:  DataTableText

name: Test

on:
  push

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      run: |
        sudo -i -u postgres psql < load.txt > output.txt
        perl upload.pl
        
