# Postgres on GitHub

name: Test

on:
  push

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo cpan -T -i JSON
        
    - name: Test
      run: |
        sudo systemctl start postgresql.service
        sudo -i -u postgres psql < load.txt > output.txt
        perl upload.pl
        
